-- NoMeuBairro — production hardening audit notes (NEW Supabase only).
-- Target project ref: gowuvofidacpdavdkpar
--
-- IMPORTANT: this file is intentionally non-executable.
-- The exact SQL that was applied to production is versioned in:
--
--   supabase/migrations/20260907165256_production_hardening_20260907.sql
--   supabase/migrations/20260907165744_production_abuse_controls_20260907_v2.sql
--
-- Those two migrations are the source of truth. Keep this database/ file only as
-- a historical pointer so an older partial hardening draft is never copied into
-- the Supabase SQL Editor by mistake.
--
-- Post-application verification queries live in:
--   database/20260907_new_supabase_security_hardening.final-verify.sql
--
-- No passwords, service-role keys, JWT secrets, VAPID private keys, dispatch
-- tokens or Vault values are stored in the repository.
