import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { supabase } from '../utils/supabase';
import { Building2, Eye, EyeOff, MapPin } from 'lucide-react';

export default function Login(){
 const nav=useNavigate();const {login}=useAuth();const [companyMode,setCompanyMode]=useState(false);const [register,setRegister]=useState(false);const [name,setName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('');const [loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setSuccess('');setLoading(true);try{if(companyMode){if(register){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{name,account_type:'company'}}});if(error){setError(error.message);return}if(!data.user){setError('Não foi possível criar a conta.');return}const {error:pe}=await supabase.from('company_profiles').insert({id:data.user.id,company_name:name,email});if(pe){setError(pe.message);return}setSuccess('Conta criada! Confirme seu e-mail para ativá-la.');setRegister(false)}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);return}const {data:cp}=await supabase.from('company_profiles').select('id').eq('id',data.user.id).maybeSingle();if(!cp){await supabase.auth.signOut();setError('Esta conta não é empresarial.');return}nav('/empresa')}}else{const r=await login(email,password);if(!r.ok){setError(r.error||'Login não realizado.');return}nav('/perfil')}}catch{setError('Ocorreu um erro. Tente novamente.')}finally{setLoading(false)}};
 return <div className="min-h-[80vh] flex items-center justify-center px-4 py-12"><div className="w-full max-w-md"><div className="text-center mb-8"><div className="inline-flex w-16 h-16 rounded-2xl bg-emerald-600 items-center justify-center mb-4">{companyMode?<Building2 className="w-8 h-8 text-white"/>:<MapPin className="w-8 h-8 text-white"/>}</div><h1 className="text-xl font-bold">{companyMode?(register?'Criar conta empresarial':'Área da Empresa'):(register?'Criar conta':'Bem-vindo de volta')}</h1><p className="text-sm text-slate-500 mt-1">{companyMode?'Publique e gerencie suas vagas.':'Entre para participar da comunidade.'}</p></div><div className="bg-white dark:bg-slate-900 rounded-2xl ring-1 ring-slate-200 dark:ring-slate-800 p-6 sm:p-8"><form onSubmit={submit} className="space-y-4">{register&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder={companyMode?'Nome da empresa':'Nome completo'} className="w-full px-4 py-3 rounded-xl border bg-white dark:bg-slate-800"/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="seu@email.com" className="w-full px-4 py-3 rounded-xl border bg-white dark:bg-slate-800"/><div className="relative"><input required minLength={6} type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Senha" className="w-full px-4 py-3 pr-12 rounded-xl border bg-white dark:bg-slate-800"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400">{show?<EyeOff/>:<Eye/>}</button></div>{error&&<p className="text-sm text-red-500">{error}</p>}{success&&<p className="text-sm text-emerald-600">{success}</p>}<button disabled={loading} className="w-full py-3 rounded-xl bg-emerald-600 text-white font-semibold disabled:opacity-50">{loading?'Aguarde...':register?'Criar conta':companyMode?'Entrar como empresa':'Entrar'}</button></form><div className="mt-5 space-y-2"><button onClick={()=>setRegister(!register)} className="w-full text-sm text-emerald-600 font-semibold">{register?'Já tenho conta':'Criar uma conta'}</button><button onClick={()=>{setCompanyMode(!companyMode);setRegister(false);setError('');}} className="w-full text-sm text-slate-500 flex items-center justify-center gap-2"><Building2 className="w-4 h-4"/>{companyMode?'Sou morador':'Sou uma empresa'}</button></div></div></div></div>;
}
