-- Production monitoring with privacy-preserving daily aggregation (migration 20260829164318).
-- No IP address, email, full URL, post ID, or user ID is stored.

create table if not exists public.production_event_daily (
  day date not null,
  fingerprint text not null check (char_length(fingerprint) = 64),
  event_type text not null check (event_type in (
    'client_error', 'render_error', 'resource_error',
    'api_error', 'api_slow', 'page_slow'
  )),
  severity text not null check (severity in ('warning', 'error', 'critical')),
  path text not null check (char_length(path) between 1 and 120),
  target text null check (target is null or char_length(target) <= 160),
  message text not null check (char_length(message) between 1 and 500),
  status_code integer null check (status_code between 100 and 599),
  device_class text null check (device_class in ('mobile', 'tablet', 'desktop')),
  release text null check (release is null or char_length(release) <= 80),
  samples integer not null default 1 check (samples > 0),
  duration_samples integer not null default 0 check (duration_samples >= 0),
  total_duration_ms bigint not null default 0 check (total_duration_ms >= 0),
  max_duration_ms integer null check (max_duration_ms between 0 and 120000),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (day, fingerprint)
);

create index if not exists production_event_daily_last_seen_idx
  on public.production_event_daily(last_seen_at desc);
create index if not exists production_event_daily_type_day_idx
  on public.production_event_daily(event_type, day desc);

create table if not exists public.production_alerts (
  id bigint generated by default as identity primary key,
  fingerprint text not null check (char_length(fingerprint) = 64),
  event_type text not null check (event_type in (
    'client_error', 'render_error', 'resource_error',
    'api_error', 'api_slow', 'page_slow'
  )),
  severity text not null check (severity in ('warning', 'error', 'critical')),
  path text not null check (char_length(path) between 1 and 120),
  target text null check (target is null or char_length(target) <= 160),
  message text not null check (char_length(message) between 1 and 500),
  status_code integer null check (status_code between 100 and 599),
  occurrences integer not null default 1 check (occurrences > 0),
  status text not null default 'open' check (status in ('open', 'resolved')),
  first_triggered_at timestamptz not null default now(),
  last_triggered_at timestamptz not null default now(),
  resolved_at timestamptz null,
  resolved_by uuid null references public.users(id) on delete set null
);

create unique index if not exists production_alerts_open_fingerprint_idx
  on public.production_alerts(fingerprint) where status = 'open';
create index if not exists production_alerts_status_last_seen_idx
  on public.production_alerts(status, last_triggered_at desc);
create index if not exists production_alerts_resolved_by_idx
  on public.production_alerts(resolved_by) where resolved_by is not null;

alter table public.production_event_daily enable row level security;
alter table public.production_alerts enable row level security;

revoke all on table public.production_event_daily from public, anon, authenticated;
revoke all on table public.production_alerts from public, anon, authenticated;
grant select on table public.production_event_daily to authenticated;
grant select on table public.production_alerts to authenticated;
grant update (status, resolved_at, resolved_by) on table public.production_alerts to authenticated;

drop policy if exists production_event_daily_moderator_select on public.production_event_daily;
create policy production_event_daily_moderator_select
  on public.production_event_daily for select to authenticated
  using ((select public.is_moderator()));

drop policy if exists production_alerts_moderator_select on public.production_alerts;
create policy production_alerts_moderator_select
  on public.production_alerts for select to authenticated
  using ((select public.is_moderator()));

drop policy if exists production_alerts_moderator_update on public.production_alerts;
create policy production_alerts_moderator_update
  on public.production_alerts for update to authenticated
  using ((select public.is_moderator()))
  with check ((select public.is_moderator()));

create or replace function private.log_production_event_internal(
  p_event_type text,
  p_path text default '/',
  p_target text default null,
  p_message text default null,
  p_duration_ms integer default null,
  p_status_code integer default null,
  p_device_class text default null,
  p_release text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_day date := (now() at time zone 'America/Sao_Paulo')::date;
  v_event_type text := lower(trim(coalesce(p_event_type, '')));
  v_path text := left(split_part(coalesce(nullif(trim(p_path), ''), '/'), '?', 1), 120);
  v_target text := nullif(left(trim(coalesce(p_target, '')), 160), '');
  v_message text := left(trim(coalesce(p_message, 'Falha sem detalhes')), 500);
  v_normalized_message text;
  v_status_code integer := case when p_status_code between 100 and 599 then p_status_code else null end;
  v_duration_ms integer := case when p_duration_ms between 0 and 120000 then p_duration_ms else null end;
  v_device_class text := case when p_device_class in ('mobile', 'tablet', 'desktop') then p_device_class else null end;
  v_release text := nullif(left(trim(coalesce(p_release, '')), 80), '');
  v_severity text;
  v_fingerprint text;
  v_samples integer;
  v_distinct_events integer;
  v_should_alert boolean;
  v_alert_id bigint;
begin
  if v_event_type not in (
    'client_error', 'render_error', 'resource_error',
    'api_error', 'api_slow', 'page_slow'
  ) then
    return jsonb_build_object('accepted', false, 'reason', 'unsupported_event');
  end if;

  if v_path !~ '^/' then v_path := '/' || v_path; end if;
  if v_path ~ '^/post/' then v_path := '/post/:id'; end if;
  if v_path ~ '^/perfil/' then v_path := '/perfil/:id'; end if;
  if v_path ~ '^/empresa/' then v_path := '/empresa/:id'; end if;
  if v_path not in (
    '/', '/mapa', '/estatisticas', '/empregos', '/mural', '/denuncias',
    '/perfil', '/perfil/:id', '/post/:id', '/empresa', '/empresa/:id',
    '/notificacoes', '/salvos', '/admin', '/privacidade', '/termos', '/login'
  ) then
    v_path := '/';
  end if;

  if v_target is not null and v_target !~ '^[a-zA-Z0-9_./:-]+$' then
    v_target := 'app';
  end if;

  -- Expected validation/auth responses are not production incidents.
  if v_event_type = 'api_error'
     and v_status_code is not null
     and v_status_code not in (408, 425, 429)
     and v_status_code < 500 then
    return jsonb_build_object('accepted', false, 'reason', 'expected_http_status');
  end if;

  if v_event_type = 'api_slow' and coalesce(v_duration_ms, 0) < 4000 then
    return jsonb_build_object('accepted', false, 'reason', 'below_slow_threshold');
  end if;
  if v_event_type = 'page_slow' and coalesce(v_duration_ms, 0) < 200 then
    return jsonb_build_object('accepted', false, 'reason', 'below_slow_threshold');
  end if;

  -- Remove identifiers and secrets before both storage and fingerprinting.
  v_message := pg_catalog.regexp_replace(v_message, '(?i)https?://[^[:space:]]+', '[url]', 'g');
  v_message := pg_catalog.regexp_replace(v_message, '(?i)[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}', '[email]', 'g');
  v_message := pg_catalog.regexp_replace(v_message, '(?i)[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}', '[id]', 'g');
  v_message := pg_catalog.regexp_replace(v_message, '[A-Za-z0-9_-]{40,}', '[token]', 'g');
  v_message := left(coalesce(nullif(trim(v_message), ''), 'Falha sem detalhes'), 500);
  v_normalized_message := lower(pg_catalog.regexp_replace(v_message, '[0-9]{4,}', '[n]', 'g'));

  v_severity := case
    when v_event_type in ('render_error', 'resource_error', 'api_error') then 'critical'
    when v_event_type = 'client_error' then 'error'
    else 'warning'
  end;

  v_fingerprint := pg_catalog.encode(
    extensions.digest(
      pg_catalog.convert_to(concat_ws('|', v_event_type, v_path, coalesce(v_target, ''), coalesce(v_status_code::text, ''), v_normalized_message), 'UTF8'),
      'sha256'
    ),
    'hex'
  );

  if not exists (
    select 1 from public.production_event_daily
    where day = v_day and fingerprint = v_fingerprint
  ) then
    select count(*)::integer into v_distinct_events
    from public.production_event_daily where day = v_day;
    if v_distinct_events >= 500 then
      return jsonb_build_object('accepted', false, 'reason', 'daily_cardinality_limit');
    end if;
  end if;

  insert into public.production_event_daily (
    day, fingerprint, event_type, severity, path, target, message,
    status_code, device_class, release, samples, duration_samples,
    total_duration_ms, max_duration_ms, first_seen_at, last_seen_at
  ) values (
    v_day, v_fingerprint, v_event_type, v_severity, v_path, v_target, v_message,
    v_status_code, v_device_class, v_release, 1,
    case when v_duration_ms is null then 0 else 1 end,
    coalesce(v_duration_ms, 0), v_duration_ms, now(), now()
  )
  on conflict (day, fingerprint) do update set
    samples = public.production_event_daily.samples + 1,
    duration_samples = public.production_event_daily.duration_samples + case when excluded.max_duration_ms is null then 0 else 1 end,
    total_duration_ms = public.production_event_daily.total_duration_ms + excluded.total_duration_ms,
    max_duration_ms = greatest(public.production_event_daily.max_duration_ms, excluded.max_duration_ms),
    last_seen_at = now(),
    release = coalesce(excluded.release, public.production_event_daily.release)
  returning samples into v_samples;

  v_should_alert := v_event_type in ('client_error', 'render_error', 'resource_error', 'api_error')
    or (v_event_type in ('api_slow', 'page_slow') and v_samples >= 3);

  if v_should_alert then
    insert into public.production_alerts (
      fingerprint, event_type, severity, path, target, message,
      status_code, occurrences, status, first_triggered_at, last_triggered_at
    ) values (
      v_fingerprint, v_event_type, v_severity, v_path, v_target, v_message,
      v_status_code, v_samples, 'open', now(), now()
    )
    on conflict (fingerprint) where status = 'open' do update set
      severity = excluded.severity,
      path = excluded.path,
      target = excluded.target,
      message = excluded.message,
      status_code = excluded.status_code,
      occurrences = public.production_alerts.occurrences + 1,
      last_triggered_at = now()
    returning id into v_alert_id;
  end if;

  return jsonb_build_object(
    'accepted', true,
    'fingerprint', v_fingerprint,
    'samples', v_samples,
    'alertId', v_alert_id
  );
end;
$function$;

revoke all on function private.log_production_event_internal(text,text,text,text,integer,integer,text,text) from public;
grant usage on schema private to anon, authenticated;
grant execute on function private.log_production_event_internal(text,text,text,text,integer,integer,text,text) to anon, authenticated;

create or replace function public.log_production_event(
  p_event_type text,
  p_path text default '/',
  p_target text default null,
  p_message text default null,
  p_duration_ms integer default null,
  p_status_code integer default null,
  p_device_class text default null,
  p_release text default null
)
returns jsonb
language sql
security invoker
set search_path = ''
as $function$
  select private.log_production_event_internal(
    p_event_type, p_path, p_target, p_message, p_duration_ms,
    p_status_code, p_device_class, p_release
  );
$function$;

revoke all on function public.log_production_event(text,text,text,text,integer,integer,text,text) from public;
grant execute on function public.log_production_event(text,text,text,text,integer,integer,text,text) to anon, authenticated;

create or replace function public.get_production_monitoring(p_days integer default 7)
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $function$
declare
  v_days integer := least(greatest(coalesce(p_days, 7), 1), 45);
  v_result jsonb;
begin
  if not public.is_moderator() then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'generatedAt', now(),
    'summary', jsonb_build_object(
      'openAlerts', (select count(*) from public.production_alerts where status = 'open'),
      'criticalOpenAlerts', (select count(*) from public.production_alerts where status = 'open' and severity = 'critical'),
      'clientErrors24h', (select coalesce(sum(samples), 0) from public.production_event_daily where last_seen_at >= now() - interval '24 hours' and event_type in ('client_error', 'render_error', 'resource_error')),
      'apiFailures24h', (select coalesce(sum(samples), 0) from public.production_event_daily where last_seen_at >= now() - interval '24 hours' and event_type = 'api_error'),
      'slowPages24h', (select coalesce(sum(samples), 0) from public.production_event_daily where last_seen_at >= now() - interval '24 hours' and event_type = 'page_slow'),
      'slowApis24h', (select coalesce(sum(samples), 0) from public.production_event_daily where last_seen_at >= now() - interval '24 hours' and event_type = 'api_slow'),
      'latestEventAt', (select max(last_seen_at) from public.production_event_daily)
    ),
    'alerts', (
      select coalesce(jsonb_agg(to_jsonb(a) order by a.last_triggered_at desc), '[]'::jsonb)
      from (
        select id, fingerprint, event_type, severity, path, target, message,
               status_code, occurrences, status, first_triggered_at,
               last_triggered_at, resolved_at
        from public.production_alerts
        order by (status = 'open') desc, last_triggered_at desc
        limit 60
      ) a
    ),
    'events', (
      select coalesce(jsonb_agg(to_jsonb(e) order by e.last_seen_at desc), '[]'::jsonb)
      from (
        select day, fingerprint, event_type, severity, path, target, message,
               status_code, device_class, release, samples,
               case when duration_samples > 0 then round(total_duration_ms::numeric / duration_samples)::integer else null end as avg_duration_ms,
               max_duration_ms, first_seen_at, last_seen_at
        from public.production_event_daily
        where day >= (now() at time zone 'America/Sao_Paulo')::date - (v_days - 1)
        order by last_seen_at desc
        limit 120
      ) e
    )
  ) into v_result;

  return v_result;
end;
$function$;

revoke all on function public.get_production_monitoring(integer) from public, anon;
grant execute on function public.get_production_monitoring(integer) to authenticated;

create or replace function public.resolve_production_alert(p_alert_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = ''
as $function$
begin
  if not public.is_moderator() then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  update public.production_alerts
  set status = 'resolved', resolved_at = now(), resolved_by = (select auth.uid())
  where id = p_alert_id and status = 'open';
  return found;
end;
$function$;

revoke all on function public.resolve_production_alert(bigint) from public, anon;
grant execute on function public.resolve_production_alert(bigint) to authenticated;

-- Reuse the existing once-per-day page-view maintenance path for retention.
create or replace function private.track_page_view_internal(p_path text)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_path text := left(coalesce(nullif(trim(p_path), ''), '/'), 120);
  v_day date := (now() at time zone 'America/Sao_Paulo')::date;
  v_first_view_today boolean;
begin
  if v_path !~ '^/' then v_path := '/' || v_path; end if;
  if v_path ~ '^/post/' then v_path := '/post/:id'; end if;
  if v_path ~ '^/perfil/' then v_path := '/perfil/:id'; end if;
  if v_path ~ '^/empresa/' then v_path := '/empresa/:id'; end if;

  if v_path not in (
    '/', '/mapa', '/estatisticas', '/empregos', '/mural', '/denuncias',
    '/perfil', '/perfil/:id', '/post/:id', '/empresa', '/empresa/:id',
    '/notificacoes', '/salvos', '/admin', '/privacidade', '/termos', '/login'
  ) then
    return;
  end if;

  select not exists (
    select 1 from public.site_analytics_daily where day = v_day
  ) into v_first_view_today;

  insert into public.site_analytics_daily(day, path, views)
  values (v_day, v_path, 1)
  on conflict (day, path) do update
    set views = public.site_analytics_daily.views + 1;

  if v_first_view_today then
    delete from public.client_error_logs where created_at < now() - interval '90 days';
    delete from public.production_event_daily where day < v_day - 44;
    delete from public.production_alerts
      where status = 'resolved' and resolved_at < now() - interval '180 days';
  end if;
end;
$function$;

comment on table public.production_event_daily is
  'Daily aggregated production telemetry. Paths and messages are sanitized; no IP or user identifier is stored.';
comment on table public.production_alerts is
  'Production incidents visible only to moderators and administrators.';
